spring:
  jpa:
    properties:
      '[hypersistence.utils.enable_types_contributor]': false
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/deal
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  application:
    name: deal