spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    bootstrap-servers: kafka:29092
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 12MB
  jpa:
    properties:
      '[hypersistence.utils.enable_types_contributor]': false
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      platform: postgres

  datasource:
    url: jdbc:postgresql://postgres:5432/deal
    username: iguana
    password: postgres
    driverClassName: org.postgresql.Driver

  application:
    name: deal

server:
  port: 8082

microservice:
  base-url: http://calculator:8081