services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: iguana
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deal
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-server:7.2.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
    networks:
      - app-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - app-network

  liquibase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: liquibase
    depends_on:
      - postgres
    volumes:
      - ./statement/src/main/resources/db/changelog:/liquibase/changelog
    command:
      [
        "sh", "-c",
        "until nc -z postgres 5432; do echo waiting for db; sleep 2; done && \
         liquibase \
           --changeLogFile=changelog/main-changelog.xml \
           --url=jdbc:postgresql://postgres:5432/deal \
           --username=iguana \
           --password=postgres \
           --driver=org.postgresql.Driver \
           update"
      ]
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network


  calculator:
    build: ./calculator
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    container_name: calculator
    networks:
      - app-network

  deal:
    build: ./deal
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    container_name: deal
    depends_on:
      - kafka
    networks:
      - app-network

  statement:
    build: ./statement
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    container_name: statement
    depends_on:
      - liquibase
    networks:
      - app-network

  dossier:
    env_file:
      - .env
    build:
      context: ./dossier
      dockerfile: dockerfile
    container_name: dossier
    ports:
      - "8084:8084"
    environment:
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      - kafka
    networks:
      - app-network

  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
    container_name: gateway
    ports:
      - "8085:8085"
    networks:
      - app-network

  integration-roles:
    build:
      context: ./integration-roles
      dockerfile: dockerfile
    container_name: integration-roles
    ports:
      - "8086:8086"
    networks:
      - app-network
    depends_on:
      - redis
  frontend:
       build:
         context: ./front
         dockerfile: Dockerfile
       container_name: frontend
       ports:
         - "3000:80"
       networks:
         - app-network

volumes:
  pg_data:
  redis_data:

networks:
  app-network:
    driver: bridge
