spring:
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml

  jpa:
    properties:
      '[hypersistence.utils.enable_types_contributor]': false
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/deal
    username: iguana
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  application:
    name: statement

microservice:
  base-url: http://deal:8082

server:
  port: 8083

